name: nsgt-torch

channels:
  - default
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - numpy<1.25
  # - numba
  - scipy
  - pytorch==1.12.1
  - torchaudio==0.12.1
  - cpuonly
  # - cudatoolkit=11.6
  - tqdm
  - pysoundfile
  - ffmpeg
  - pip
  - pip:
    - matplotlib
    - line_profiler
    - memory_profiler
    - "-e ."
